import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/shared/Navbar/Navbar";
import MenuNavbar from "@/component/shared/MenuNavbar/MenuNavbar";
import Footer from "@/component/shared/Footer/Footer";
import AuthProvider from "@/component/ContextProvider/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PicVault",
  description: "Generated by PicVault",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider >
          <Navbar />
          <MenuNavbar />
          {children}
          <Footer />
        </AuthProvider >
      </body>
    </html>
  );
}
